services:
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
    restart: always

  postgres:
    image: postgres:14
    container_name: postgres-container
    ports:
      - "5434:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
