services:
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
    restart: always

  postgres:
    image: postgres:14
    container_name: postgres-container
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: