version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:bibibibibibi@postgres:5432/mydb"
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - redis
      - postgres

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
    restart: always

  postgres:
    image: postgres:14
    container_name: postgres-container
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bibibibibibi
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
